### PR TITLE
Unsigned requests

### PR DESCRIPTION
**Pull request by philhug**
Support unsigned AuthN requests.

### CODE REVIEW

**Comment by mbrevoort** [comment]
Thanks!
I know the tests are super light in this project. Would you be able to add a test to at least cover this case? :pray:

**Comment by philhug** [comment]
I added a simple test case.

**Comment by mbrevoort** [comment]
Did you forget to push?

**Comment by philhug** [comment]
@mbrevoort yes, pushed.

**Comment by mbrevoort** [comment]
Thanks @philhug! Sorry for the delay, I disappeared on vacation.

**Pull request merged**
